_wandb:
    value:
        cli_version: 0.19.10
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.12.6
            "5": 0.19.10
            "6": 4.48.1
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
beta:
    value: 0.1
dpo_mode:
    value: true
learning_rate:
    value: 1e-05
model_name:
    value: AI4PD/ZymCTRL
warmup_steps:
    value: 100
weight_decay:
    value: 0.01
